# This single manifest deploys Grafana and all its configurations.

# --- ConfigMap for grafana.ini ---
# Loads the main Grafana settings, with anonymous auth enabled.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini-config
  namespace: shopmicro
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = localhost
    root_url = http://localhost:3000
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    [security]
    admin_user = admin
    admin_password = admin
    [users]
    allow_sign_up = false
    [auth.anonymous]
    # This is modified from the original file to enable easy access for the lab.
    enabled = true
    org_name = Main Org.
    org_role = Viewer

---
# --- ConfigMap for Datasource Provisioning ---
# Loads the datasource definitions from infrastructure/grafana/provisioning/datasources/prometheus.yml
# with the Mimir URL corrected.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-config
  namespace: shopmicro
  labels:
    app: grafana
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        access: proxy
        # This URL is modified to point to the correct Kubernetes service.
        url: http://mimir-service:9009
        isDefault: true
        editable: true
        jsonData:
          timeInterval: 15s
          prometheusType: Mimir
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: true
        jsonData:
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: 'trace_id=(\w+)'
              name: TraceID
              url: '/explore?orgId=1&left=["now-1h","now","Tempo",{"query":"${__value.raw}"}]'
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        editable: true
        uid: tempo
        jsonData:
          tracesToLogs:
            datasourceUid: 'loki'

---
# --- ConfigMap for Dashboard Provisioning ---
# Loads the dashboard provider definition from infrastructure/grafana/provisioning/dashboards/dashboards.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider-config
  namespace: shopmicro
  labels:
    app: grafana
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: 'ShopMicro Dashboards'
        orgId: 1
        folder: 'ShopMicro'
        folderUid: shopmicro
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 30
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/shopmicro

---
# --- ConfigMap for all Dashboard JSON files ---
# Loads all .json files from infrastructure/grafana/dashboards/ into one ConfigMap.
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-json-config
  namespace: shopmicro
  labels:
    app: grafana
data:
  shopmicro-overview.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [
        "shopmicro",
        "overview"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "ShopMicro - Overview Dashboard",
      "uid": "shopmicro-overview",
      "version": 1,
      "weekStart": ""
    }
  ml-service.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [
        "shopmicro",
        "ml-service"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "ShopMicro - ML Service",
      "uid": "shopmicro-ml-service",
      "version": 1,
      "weekStart": ""
    }
  logs-traces.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [
        "shopmicro",
        "logs",
        "traces"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "ShopMicro - Logs & Traces",
      "uid": "shopmicro-logs-traces",
      "version": 1,
      "weekStart": ""
    }
  backend-service.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "liveNow": false,
      "panels": [],
      "refresh": "5s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [
        "shopmicro",
        "backend"
      ],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "ShopMicro - Backend Service",
      "uid": "shopmicro-backend",
      "version": 1,
      "weekStart": ""
    }
  application-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "ShopMicro - Observability Overview",
        "tags": ["shopmicro", "observability"],
        "timezone": "browser",
        "panels": [],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s",
        "schemaVersion": 27,
        "version": 1
      }
    }

---
# --- Grafana Deployment and Service ---
# The main deployment that ties all the ConfigMaps together.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: shopmicro
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.2.0
        ports:
        - name: http-grafana
          containerPort: 3000
        resources:
          requests:
            cpu: "128m"
            memory: "100Mi"
          limits:
            cpu: "256m"
            memory: "200Mi"
        volumeMounts:
        - name: grafana-ini
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources/prometheus.yml
          subPath: prometheus.yml
        - name: grafana-dashboard-provider
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
          subPath: dashboards.yml
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards/shopmicro
      volumes:
      - name: grafana-ini
        configMap:
          name: grafana-ini-config
      - name: grafana-datasources
        configMap:
          name: grafana-datasources-config
      - name: grafana-dashboard-provider
        configMap:
          name: grafana-dashboard-provider-config
      - name: grafana-dashboards
        configMap:
          name: grafana-dashboards-json-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: shopmicro
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
  - name: http-grafana
    port: 3000
    targetPort: 3000